#!/usr/bin/env node
// mps — agents.mjs
// Harness-neutral agent roles + per-harness adapters (ADR-0003).
//
// One source of truth: agents/<role>.md, whose frontmatter is neutral
// (name / description / mode / model tier / effort / access / tools). Each
// harness gets that same role rendered into ITS native format:
//
//   claude    .claude/agents/mps-<role>.md      (subagent, model opus/sonnet/haiku)
//   opencode  .opencode/agent/mps-<role>.md     (mode: subagent, tools map)
//   codex     .codex/prompts/mps-<role>.md      (custom prompt, fresh context)
//
// Everything a harness cannot express natively is still reachable the same
// way from all of them: `mps agents show <role>` prints the raw prompt, so a
// harness with neither subagents nor prompt files can spawn a fresh context
// with it (e.g. `codex exec "$(mps agents show critic)"`).
//
// Generated files carry a provenance line with the source hash, so doctor can
// tell "installed and current" from "installed and stale" without an LLM.
//
// CLI: node agents.mjs list|show|install|uninstall|register|unregister|model [args]

import { existsSync, readFileSync, readdirSync, mkdirSync, writeFileSync, unlinkSync } from "node:fs";
import { join, dirname } from "node:path";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import {
  pluginRoot,
  projectRoot,
  readConfig,
  writeConfig,
  parseFrontmatter,
  loadLayout,
  ignoreEpipe,
} from "./lib.mjs";

export const HARNESSES = ["claude", "opencode", "codex"];
export const AGENT_BLOCK_VERSION = 1;
export const AGENT_BLOCK_MARKER = /<!--\s*mps:agents v(\d+)/g;
// Roles register under an mps- prefix in every harness. Bare names (critic,
// planner, reviewer) are common enough that a user's own agent would collide;
// a prefix keeps both, and makes "which of these is ours" a string match.
export const PREFIX = "mps-";

// Neutral tier → what each harness understands. `null` means "say nothing and
// inherit the harness default" — only Claude Code has a stable public naming
// for the tiers, so pinning a model id for the others would be a guess.
const TIER = {
  claude: { reasoning: "opus", balanced: "sonnet", fast: "haiku" },
  opencode: { reasoning: null, balanced: null, fast: null },
  codex: { reasoning: null, balanced: null, fast: null },
};

const CLAUDE_TOOLS = {
  read: "Read", grep: "Grep", glob: "Glob", bash: "Bash",
  edit: "Edit", write: "Write", web: "WebFetch, WebSearch",
};

// OpenCode takes an explicit allow/deny map, so the read-only contract these
// roles are built on is enforced by the harness rather than by prose.
const OPENCODE_TOOLS = ["read", "grep", "glob", "bash", "edit", "write", "patch", "webfetch"];

export function rolesDir() {
  return join(pluginRoot(), "agents");
}

export function roleNames() {
  try {
    return readdirSync(rolesDir())
      .filter((n) => n.endsWith(".md"))
      .map((n) => n.replace(/\.md$/, ""))
      .sort();
  } catch {
    return [];
  }
}

export function readRole(name) {
  const p = join(rolesDir(), `${name}.md`);
  if (!existsSync(p)) throw new Error(`No such role: ${name} (expected ${p})`);
  const raw = readFileSync(p, "utf8");
  const { data, body } = parseFrontmatter(raw);
  const tools = String(data.tools || "")
    .replace(/^\[|\]$/g, "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
  return {
    name: data.name || name,
    description: String(data.description || "").trim(),
    mode: data.mode || "subagent",
    tier: data.model || "balanced",
    effort: data.effort || null,
    access: data.access || "read-only",
    tools,
    body: body.replace(/^\n+/, ""),
    path: p,
    hash: createHash("sha256").update(raw).digest("hex").slice(0, 12),
  };
}

export function listRoles() {
  return roleNames().map(readRole);
}

// Roster the bound layout declares, intersected with what actually ships —
// a layout naming a role we do not have is a layout bug, not an install one.
export function rosterFor(cfg) {
  const have = new Set(roleNames());
  let want = null;
  try {
    want = loadLayout((cfg && cfg.layout) || "engineering").agents || null;
  } catch { /* unknown layout: fall back to everything bundled */ }
  return (want || [...have]).filter((n) => have.has(n));
}

// Model precedence: per-role config → default config → the tier's harness
// mapping. Config wins so a project can pin a concrete id per harness without
// editing the shared role definition.
export function resolveModel(role, cfg, harness) {
  const a = (cfg && cfg.agents) || {};
  const perRole = a.per_agent && a.per_agent[role.name] && a.per_agent[role.name].model;
  const dflt = a.default && a.default.model;
  return perRole || dflt || TIER[harness][role.tier] || null;
}

function provenance(role) {
  return `<!-- generated by \`mps agents install\` from agents/${role.name}.md@${role.hash} — edit the source, not this file -->`;
}

export function installedRoleOf(text) {
  const m = String(text).match(/generated by `mps agents install` from agents\/([\w-]+)\.md@([0-9a-f]+)/);
  return m ? { role: m[1], hash: m[2] } : null;
}

function renderClaude(role, model) {
  const tools = role.tools.map((t) => CLAUDE_TOOLS[t] || t).join(", ");
  const fm = [
    "---",
    `name: ${PREFIX}${role.name}`,
    `description: ${role.description}`,
    ...(model ? [`model: ${model}`] : []),
    ...(role.effort ? [`effort: ${role.effort}`] : []),
    `tools: ${tools}`,
    "---",
  ];
  return `${fm.join("\n")}\n${provenance(role)}\n\n${role.body}`;
}

function renderOpencode(role, model) {
  const allowed = new Set(role.tools.flatMap((t) => (t === "web" ? ["webfetch"] : [t])));
  if (role.access === "read-only") { allowed.delete("edit"); allowed.delete("write"); allowed.delete("patch"); }
  const toolLines = OPENCODE_TOOLS.map((t) => `  ${t}: ${allowed.has(t)}`);
  const fm = [
    "---",
    `description: ${role.description}`,
    `mode: ${role.mode}`,
    ...(model ? [`model: ${model}`] : []),
    "tools:",
    ...toolLines,
    "---",
  ];
  return `${fm.join("\n")}\n${provenance(role)}\n\n${role.body}`;
}

// Codex has no subagent type: a prompt file is the fresh context. The
// read-only contract therefore has to be stated in prose, and is.
function renderCodex(role) {
  const fm = [
    "---",
    `description: ${role.description}`,
    'argument-hint: "<file or topic to work on>"',
    "---",
  ];
  const head = [
    `Run as the mps **${role.name}** role, in this fresh context.`,
    "",
    `Target: $ARGUMENTS`,
    "",
    role.access === "read-only"
      ? "This role is READ-ONLY: inspect, verify and report. Do not edit, stage or commit anything — every fix goes back through the approval-gated `mps` flow.\n"
      : "",
    "---",
    "",
  ].join("\n");
  return `${fm.join("\n")}\n${provenance(role)}\n\n${head}${role.body}`;
}

export function targetDir(harness, proj = projectRoot()) {
  switch (harness) {
    case "claude": return join(proj, ".claude", "agents");
    case "opencode": return join(proj, ".opencode", "agent");
    case "codex": return join(proj, ".codex", "prompts");
    default: throw new Error(`Unknown harness: ${harness} (known: ${HARNESSES.join(", ")})`);
  }
}

export function targetPath(harness, roleName, proj = projectRoot()) {
  return join(targetDir(harness, proj), `${PREFIX}${roleName}.md`);
}

export function renderFor(harness, role, cfg) {
  const model = resolveModel(role, cfg, harness);
  if (harness === "claude") return renderClaude(role, model);
  if (harness === "opencode") return renderOpencode(role, model);
  if (harness === "codex") return renderCodex(role);
  throw new Error(`Unknown harness: ${harness}`);
}

// Which harnesses this project already uses. Detection is by directory, never
// by env: a Codex user must not have .claude/ conjured for them, and a project
// shared by a team may legitimately carry all three.
export function detectHarnesses(proj = projectRoot()) {
  const seen = [];
  if (existsSync(join(proj, ".claude")) || existsSync(join(proj, "CLAUDE.md"))) seen.push("claude");
  if (existsSync(join(proj, ".opencode")) || existsSync(join(proj, "opencode.json"))) seen.push("opencode");
  if (existsSync(join(proj, ".codex"))) seen.push("codex");
  return seen;
}

export function install(harnesses, { proj = projectRoot(), cfg = readConfig() } = {}) {
  const out = [];
  for (const harness of harnesses) {
    const dir = targetDir(harness, proj);
    mkdirSync(dir, { recursive: true });
    for (const name of rosterFor(cfg)) {
      const role = readRole(name);
      const p = targetPath(harness, name, proj);
      const content = renderFor(harness, role, cfg);
      const before = existsSync(p) ? readFileSync(p, "utf8") : null;
      if (before === content) {
        out.push({ harness, role: name, path: p, action: "unchanged" });
        continue;
      }
      writeFileSync(p, content, "utf8");
      out.push({ harness, role: name, path: p, action: before === null ? "created" : "updated" });
    }
  }
  return out;
}

export function uninstall(harnesses, { proj = projectRoot() } = {}) {
  const out = [];
  for (const harness of harnesses) {
    const dir = targetDir(harness, proj);
    let names = [];
    try { names = readdirSync(dir); } catch { continue; }
    for (const n of names) {
      if (!n.startsWith(PREFIX) || !n.endsWith(".md")) continue;
      const p = join(dir, n);
      // Only remove what we generated: a file a user wrote under our prefix
      // has no provenance line and stays.
      if (!installedRoleOf(readFileSync(p, "utf8"))) continue;
      unlinkSync(p);
      out.push({ harness, path: p, action: "removed" });
    }
  }
  return out;
}

// Per-harness install state, the shape doctor reports on.
export function status({ proj = projectRoot(), cfg = readConfig() } = {}) {
  const roster = rosterFor(cfg);
  return HARNESSES.map((harness) => {
    const roles = roster.map((name) => {
      const p = targetPath(harness, name, proj);
      if (!existsSync(p)) return { role: name, state: "absent", path: p };
      const marker = installedRoleOf(readFileSync(p, "utf8"));
      if (!marker) return { role: name, state: "foreign", path: p };
      const current = readRole(name).hash === marker.hash;
      return { role: name, state: current ? "current" : "stale", path: p };
    });
    return { harness, dir: targetDir(harness, proj), roles };
  });
}

// ─── Routing block ─────────────────────────────────────────────────────

export function renderBlock(cfg) {
  const tmpl = readFileSync(join(pluginRoot(), "templates", "agents-block.md.tmpl"), "utf8");
  const roles = rosterFor(cfg).map((n) => {
    const r = readRole(n);
    const when = r.description.split(/(?<=\.)\s/)[0];
    return `- \`${PREFIX}${n}\` — ${when}`;
  }).join("\n");
  return tmpl
    .replace(/\{\{version\}\}/g, String(AGENT_BLOCK_VERSION))
    .replace(/\{\{roles\}\}/g, roles);
}

const BLOCK_RE = /<!--\s*mps:agents v\d+[\s\S]*?<!--\s*\/mps:agents\s*-->\n?/g;

// Register into every instruction file the project actually has. Idempotent:
// an existing block is replaced in place (never duplicated), which is also how
// a version bump propagates.
export function register({ proj = projectRoot(), cfg = readConfig(), files = null } = {}) {
  const block = renderBlock(cfg);
  const targets = files || ["AGENTS.md", "CLAUDE.md"].filter((f) => existsSync(join(proj, f)));
  const out = [];
  for (const f of (targets.length ? targets : ["AGENTS.md"])) {
    const p = join(proj, f);
    const before = existsSync(p) ? readFileSync(p, "utf8") : "";
    const next = BLOCK_RE.test(before)
      ? before.replace(BLOCK_RE, block)
      : `${before.replace(/\s*$/, "")}\n\n${block}`;
    BLOCK_RE.lastIndex = 0;
    if (next === before) { out.push({ file: f, action: "unchanged" }); continue; }
    mkdirSync(dirname(p), { recursive: true });
    writeFileSync(p, next, "utf8");
    out.push({ file: f, action: before ? "updated" : "created" });
  }
  return out;
}

export function unregister({ proj = projectRoot() } = {}) {
  const out = [];
  for (const f of ["AGENTS.md", "CLAUDE.md"]) {
    const p = join(proj, f);
    if (!existsSync(p)) continue;
    const before = readFileSync(p, "utf8");
    const next = before.replace(BLOCK_RE, "").replace(/\n{3,}$/, "\n");
    BLOCK_RE.lastIndex = 0;
    if (next === before) continue;
    writeFileSync(p, next, "utf8");
    out.push({ file: f, action: "removed" });
  }
  return out;
}

// ─── CLI ───────────────────────────────────────────────────────────────

function die(msg) {
  process.stderr.write(`mps agents: ${msg}\n`);
  process.exit(1);
}

function harnessArg(rest, cfg) {
  const i = rest.indexOf("--harness");
  const raw = i !== -1 ? rest[i + 1] : null;
  if (!raw || raw === "all") {
    if (raw === "all") return HARNESSES;
    const seen = detectHarnesses();
    return seen.length ? seen : HARNESSES;
  }
  const list = raw.split(",").map((s) => s.trim());
  for (const h of list) if (!HARNESSES.includes(h)) die(`unknown harness "${h}" (known: ${HARNESSES.join(", ")}, all)`);
  return list;
}

function main() {
  ignoreEpipe();
  const [sub = "list", ...rest] = process.argv.slice(2);
  const cfg = readConfig();
  const json = rest.includes("--json");
  switch (sub) {
    case "list": {
      const st = status({ cfg });
      if (json) { process.stdout.write(JSON.stringify({ roles: listRoles().map(({ body, ...r }) => r), install: st }, null, 2) + "\n"); return; }
      for (const r of listRoles()) {
        process.stdout.write(`${PREFIX}${r.name}  [${r.tier}/${r.effort || "default"}, ${r.access}]\n  ${r.description.split(". ")[0]}.\n`);
      }
      process.stdout.write("\nInstalled:\n");
      for (const h of st) {
        const by = h.roles.reduce((a, x) => ({ ...a, [x.state]: (a[x.state] || 0) + 1 }), {});
        const summary = Object.entries(by).map(([k, v]) => `${v} ${k}`).join(", ");
        process.stdout.write(`  ${h.harness.padEnd(9)} ${summary}  (${h.dir})\n`);
      }
      return;
    }
    case "show": {
      const name = rest[0];
      if (!name) die('show <role> — one of: ' + roleNames().join(", "));
      const role = readRole(name.replace(new RegExp(`^${PREFIX}`), ""));
      const target = rest.slice(1).filter((a) => !a.startsWith("--")).join(" ");
      process.stdout.write((target ? `Target: ${target}\n\n` : "") + role.body);
      return;
    }
    case "install": {
      const res = install(harnessArg(rest, cfg), { cfg });
      if (json) { process.stdout.write(JSON.stringify(res, null, 2) + "\n"); return; }
      for (const r of res) process.stdout.write(`${r.action.padEnd(9)} ${r.path}\n`);
      if (res.some((r) => r.harness === "codex")) {
        process.stdout.write("\nCodex reads prompts from ~/.codex/prompts — copy them there to get slash commands:\n  cp .codex/prompts/mps-*.md ~/.codex/prompts/\n");
      }
      return;
    }
    case "uninstall": {
      const res = uninstall(harnessArg(rest, cfg));
      if (json) { process.stdout.write(JSON.stringify(res, null, 2) + "\n"); return; }
      if (!res.length) process.stdout.write("nothing to remove\n");
      for (const r of res) process.stdout.write(`removed  ${r.path}\n`);
      return;
    }
    case "register": {
      const res = register({ cfg });
      for (const r of res) process.stdout.write(`${r.action.padEnd(9)} ${r.file}\n`);
      return;
    }
    case "unregister": {
      const res = unregister();
      if (!res.length) process.stdout.write("no routing block found\n");
      for (const r of res) process.stdout.write(`removed  ${r.file}\n`);
      return;
    }
    case "model": {
      const [who, model] = rest;
      if (!who || !model) die('model <role|default> <model-id>');
      const next = { ...(cfg || {}) };
      if (!next.vault_path) die("no bound vault — run `mps bind <vault-path>` first");
      next.agents = next.agents || {};
      if (who === "default") next.agents.default = { ...(next.agents.default || {}), model };
      else {
        if (!roleNames().includes(who)) die(`unknown role "${who}" (known: ${roleNames().join(", ")}, default)`);
        next.agents.per_agent = next.agents.per_agent || {};
        next.agents.per_agent[who] = { ...(next.agents.per_agent[who] || {}), model };
      }
      writeConfig(next);
      process.stdout.write(`agents.${who === "default" ? "default" : `per_agent.${who}`}.model = ${model}\nRe-run \`mps agents install\` to re-render the harness files.\n`);
      return;
    }
    default:
      die(`unknown subcommand "${sub}" (list|show|install|uninstall|register|unregister|model)`);
  }
}

if (process.argv[1] && process.argv[1] === fileURLToPath(import.meta.url)) main();
